# This is a basic workflow to help you get started with Actions

name: Build BSP

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install Tools
        shell: bash
        run: |
          sudo apt-get -qq update
          sudo apt-get -qq install scons
          scons --version
          pip install empy
          pip install pexpect
          pip install dronecan
          
      - name: Install Arm ToolChains
        shell: bash
        run: |
          wget -q https://developer.arm.com/-/media/Files/downloads/gnu-rm/7-2018q2/gcc-arm-none-eabi-7-2018-q2-update-linux.tar.bz2
          sudo tar xjf gcc-arm-none-eabi-7-2018-q2-update-linux.tar.bz2 -C /opt
          /opt/gcc-arm-none-eabi-7-2018-q2-update/bin/arm-none-eabi-gcc --version
          echo "RTT_EXEC_PATH=/opt/gcc-arm-none-eabi-7-2018-q2-update/bin" >> $GITHUB_ENV
          
      - name: Compile BSP
        run: |
          scons -C target/amov/icf5 -j4
          scons -C target/amov/icf5 -j4 --vehicle=Fixwing
          scons -C target/pixhawk/fmu-v2 -j4
          scons -C target/pixhawk/fmu-v5 -j4
          scons -C target/cuav/v5_plus -j4
          scons -C target/cubepilot/cubeorange -j4
          scons -C target/qemu/qemu-vexpress-a9 -j4
